/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScholarshipRouteImport } from './routes/scholarship'
import { Route as PressRouteImport } from './routes/press'
import { Route as NewspaperRouteImport } from './routes/newspaper'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ExcosRouteImport } from './routes/excos'
import { Route as EventRouteImport } from './routes/event'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ScholarshipRoute = ScholarshipRouteImport.update({
  id: '/scholarship',
  path: '/scholarship',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const NewspaperRoute = NewspaperRouteImport.update({
  id: '/newspaper',
  path: '/newspaper',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcosRoute = ExcosRouteImport.update({
  id: '/excos',
  path: '/excos',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/event': typeof EventRoute
  '/excos': typeof ExcosRoute
  '/gallery': typeof GalleryRoute
  '/newspaper': typeof NewspaperRoute
  '/press': typeof PressRoute
  '/scholarship': typeof ScholarshipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/event': typeof EventRoute
  '/excos': typeof ExcosRoute
  '/gallery': typeof GalleryRoute
  '/newspaper': typeof NewspaperRoute
  '/press': typeof PressRoute
  '/scholarship': typeof ScholarshipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/event': typeof EventRoute
  '/excos': typeof ExcosRoute
  '/gallery': typeof GalleryRoute
  '/newspaper': typeof NewspaperRoute
  '/press': typeof PressRoute
  '/scholarship': typeof ScholarshipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/event'
    | '/excos'
    | '/gallery'
    | '/newspaper'
    | '/press'
    | '/scholarship'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/event'
    | '/excos'
    | '/gallery'
    | '/newspaper'
    | '/press'
    | '/scholarship'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/event'
    | '/excos'
    | '/gallery'
    | '/newspaper'
    | '/press'
    | '/scholarship'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ArticlesRoute: typeof ArticlesRoute
  EventRoute: typeof EventRoute
  ExcosRoute: typeof ExcosRoute
  GalleryRoute: typeof GalleryRoute
  NewspaperRoute: typeof NewspaperRoute
  PressRoute: typeof PressRoute
  ScholarshipRoute: typeof ScholarshipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scholarship': {
      id: '/scholarship'
      path: '/scholarship'
      fullPath: '/scholarship'
      preLoaderRoute: typeof ScholarshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newspaper': {
      id: '/newspaper'
      path: '/newspaper'
      fullPath: '/newspaper'
      preLoaderRoute: typeof NewspaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excos': {
      id: '/excos'
      path: '/excos'
      fullPath: '/excos'
      preLoaderRoute: typeof ExcosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ArticlesRoute: ArticlesRoute,
  EventRoute: EventRoute,
  ExcosRoute: ExcosRoute,
  GalleryRoute: GalleryRoute,
  NewspaperRoute: NewspaperRoute,
  PressRoute: PressRoute,
  ScholarshipRoute: ScholarshipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
